export default Object.freeze({
	MODAL_OPEN: 'MODAL_OPEN',
	MODAL_CLOSE: 'MODAL_CLOSE',

	ALIASES_REQUEST: 'ALIASES_REQUEST',
	ALIASES_SUCCESS: 'ALIASES_SUCCESS',
	ALIASES_FAILURE: 'ALIASES_FAILURE',

	CREATE_ALIAS_REQUEST: 'CREATE_ALIAS_REQUEST',
	CREATE_ALIAS_SUCCESS: 'CREATE_ALIAS_SUCCESS',
	CREATE_ALIAS_FAILURE: 'CREATE_ALIAS_FAILURE',

	INVALIDATE_ALIASES: 'INVALIDATE_ALIASES',
});
