export default Object.freeze({
	MODAL_OPEN: 'MODAL_OPEN',
	MODAL_CLOSE: 'MODAL_CLOSE',

	MENU_OPEN: 'MENU_OPEN',
	MENU_CLOSE: 'MENU_CLOSE',

	GOS_REQUEST: 'GOS_REQUEST',
	GOS_SUCCESS: 'GOS_SUCCESS',
	GOS_FAILURE: 'GOS_FAILURE',

	CREATE_GO_REQUEST: 'CREATE_GO_REQUEST',
	CREATE_GO_SUCCESS: 'CREATE_GO_SUCCESS',
	CREATE_GO_FAILURE: 'CREATE_GO_FAILURE',

	DELETE_GO_REQUEST: 'DELETE_GO_REQUEST',
	DELETE_GO_SUCCESS: 'DELETE_GO_SUCCESS',
	DELETE_GO_FAILURE: 'DELETE_GO_FAILURE',

	INVALIDATE_GOS: 'INVALIDATE_GOS',
});
