export default Object.freeze({
	CREATE_GO: 'CREATE_GO',
	DELETE_GO: 'DELETE_GO',
	DELETE_GO_FAIL: 'DELETE_GO_FAIL',
	GO_MENU: 'GO_MENU',
	CREATE_GO_SUCCESS: 'CREATE_GO_SUCCESS',
	CREATE_GO_FAIL: 'CREATE_GO_FAIL',
	COPY_URL: 'COPY_URL',
	COPY_URL_FAIL: 'COPY_URL_FAIL',
});
