export const CREATE_GO_DIALOG = 'CREATE_GO_DIALOG';
export const DELETE_GO_SNACK = 'DELETE_GO_SNACK';
export const DELETE_GO_FAIL_SNACK = 'DELETE_GO_FAIL_SNACK';
export const GO_MENU = 'GO_MENU';
export const CREATE_GO_SNACK = 'CREATE_GO_SNACK';
export const CREATE_GO_FAIL_SNACK = 'CREATE_GO_FAIL_SNACK';
export const COPY_URL_SNACK = 'COPY_URL_SNACK';
export const COPY_URL_FAIL_SNACK = 'COPY_URL_FAIL_SNACK';
