apiVersion: apps/v1
kind: Deployment
metadata:
  name: yougo-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: yougo-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        deployment: yougo-ui
    spec:
      containers:
        - name: yougo-ui
          image: quay.io/yougo-app/yougo-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config
              mountPath: /opt/app-root/src/config.js
              subPath: config.js
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: ui-config
