apiVersion: v1
kind: Service
metadata:
  name: yougo-ui
spec:
  type: ClusterIP
  selector:
    deployment: yougo-ui
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
