apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  name: yougo-ui
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: {}
      from:
        kind: DockerImage
        name: quay.io/yougo-app/yougo-ui
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
