apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yougo
commonLabels:
  app: yougo-ui
  app.kubernetes.io/name: yougo-ui
  app.kubernetes.io/component: ui
  app.kubernetes.io/part-of: yougo

resources:
  - deployment.yml
  - imagestream.yml
  - route.yml
  - service.yml
