const env = require('react-scripts/config/env')().raw;
['NODE_ENV', 'PUBLIC_URL'].forEach(key => {
	delete env[key];
});

console.log(`
// Auto-generated by build-env.js, DO NOT EDIT
window.env = ${JSON.stringify(env, null, 2)}`.trim(),
);