apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: yougo-ui
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/yougo-app/yougo-ui:latest
      importPolicy: {}
      referencePolicy:
        type: Source
