apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yougo
commonLabels:
  app: yougo-ui
  app.kubernetes.io/name: yougo-ui
  app.kubernetes.io/component: ui
  app.kubernetes.io/part-of: yougo

resources:
  - ../base
  - imagestream.yml
  - route.yml

patches:
  - path: patches/deployment.yml

images:
  - name: quay.io/yougo-app/yougo-ui
    newName: yougo-ui
    newTag: latest
