apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yougo-ui
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: yougo-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
